#!/bin/bash

# TODO: Need to do more variable checking like in update-local-repo
cd /home/$SUDO_USER/Downloads
tar xzvf tailscale_*_arm64.tgz
systemctl stop tailscaled

install -p tailscale_*_arm64/tailscale /bin
install -p tailscale_*_arm64/tailscaled /bin

systemctl daemon-reload
systemctl start tailscaled
# systemctl status tailscaled

tailscale version
# tailscale status

rm -fvr tailscale_*_arm64
